---
- name: Install and start nginx services
  hosts: all
  become: true
  tasks: 
  - name: apt-get update
    apt: 
      name: nginx
      state: latest

  - name: start nginx
    service: 
      name: nginx
      state: started

